-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 15:10:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema matwente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema matwente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matwente` DEFAULT CHARACTER SET utf8 ;
USE `matwente` ;

-- -----------------------------------------------------
-- Table `matwente`.`afdeling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`afdeling` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `afdeling_naam` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO matwente.afdeling (afdeling_naam) VALUES ('CAD'), ('Directie'), ('Engineering'), ('Financiele Administratie'), ('HRM'), ('ICT'), ('Onderzoek'), ('Planning'), ('Project Planning'), ('Verkoop en Marketing');


-- -----------------------------------------------------
-- Table `matwente`.`geslacht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`geslacht` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `geslacht_naam` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO matwente.geslacht (geslacht_naam) VALUES ('Dhr.'), ('Mevr.');
-- -----------------------------------------------------
-- Table `matwente`.`medewerkers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`medewerkers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `afdeling_id` INT NOT NULL,
  `geslacht_id` INT NOT NULL,
  `voornaam` VARCHAR(45) NULL,
  `tussenvoegsel` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  `inter_telefoonnummer` INT NULL,
  PRIMARY KEY (`id`, `geslacht_id`),
  INDEX `fk_medewerkers_afdeling_idx` (`afdeling_id` ASC),
  INDEX `fk_medewerkers_geslacht1_idx` (`geslacht_id` ASC),
  CONSTRAINT `fk_medewerkers_afdeling`
    FOREIGN KEY (`afdeling_id`)
    REFERENCES `matwente`.`afdeling` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medewerkers_geslacht1`
    FOREIGN KEY (`geslacht_id`)
    REFERENCES `matwente`.`geslacht` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO matwente.medewerkers (afdeling_id, geslacht_id, voornaam, tussenvoegsel, achternaam, inter_telefoonnummer) VALUES (1, 2, 'V', '', 'Campbell', '12345');

-- -----------------------------------------------------
-- Table `matwente`.`verantwoordelijke`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`verantwoordelijke` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NULL,
  `medewerkers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `medewerkers_id`),
  INDEX `fk_verantwoordelijke_medewerkers1_idx` (`medewerkers_id` ASC),
  CONSTRAINT `fk_verantwoordelijke_medewerkers1`
    FOREIGN KEY (`medewerkers_id`)
    REFERENCES `matwente`.`medewerkers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO matwente.verantwoordelijke (naam, medewerkers_id) VALUES ('v', 1);


-- -----------------------------------------------------
-- Table `matwente`.`melding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`melding` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `verantwoordelijke_id` INT NOT NULL,
  `aanmeld_dag` VARCHAR(45) NULL,
  `meer_informatie` VARCHAR(45) NULL,
  `korte_omschrijving` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_melding_verantwoordelijke1_idx` (`verantwoordelijke_id` ASC),
  CONSTRAINT `fk_melding_verantwoordelijke1`
    FOREIGN KEY (`verantwoordelijke_id`)
    REFERENCES `matwente`.`verantwoordelijke` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO matwente.melding (verantwoordelijke_id, aanmeld_dag, meer_informatie, korte_omschrijving) VALUES (1, '23', 'Meer informatie!', 'Korte omschrijving!');


-- -----------------------------------------------------
-- Table `matwente`.`oplossing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`oplossing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `oorzaak` TEXT NULL,
  `oplossing` TEXT NULL,
  `terugkoppeling` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO matwente.oplossing (oorzaak, oplossing, terugkoppeling) VALUES ('Oorzaak', 'Oplossing', 'Terugkoppeling');

-- -----------------------------------------------------
-- Table `matwente`.`melding_has_oplossing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`melding_has_oplossing` (
  `melding_id` INT NOT NULL,
  `oplossing_id` INT NOT NULL,
  PRIMARY KEY (`melding_id`, `oplossing_id`),
  INDEX `fk_melding_has_oplossing_oplossing1_idx` (`oplossing_id` ASC),
  INDEX `fk_melding_has_oplossing_melding1_idx` (`melding_id` ASC),
  CONSTRAINT `fk_melding_has_oplossing_melding1`
    FOREIGN KEY (`melding_id`)
    REFERENCES `matwente`.`melding` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_melding_has_oplossing_oplossing1`
    FOREIGN KEY (`oplossing_id`)
    REFERENCES `matwente`.`oplossing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matwente`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO matwente.status (status_type) VALUES ('admin');

-- -----------------------------------------------------
-- Table `matwente`.`gebruikersccount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`gebruikersccount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medewerkers_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `wachtwoord` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `medewerkers_id`),
  INDEX `fk_gebruikersccount_medewerkers1_idx` (`medewerkers_id` ASC),
  INDEX `fk_gebruikersccount_status1_idx` (`status_id` ASC),
  CONSTRAINT `fk_gebruikersccount_medewerkers1`
    FOREIGN KEY (`medewerkers_id`)
    REFERENCES `matwente`.`medewerkers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gebruikersccount_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `matwente`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO matwente.gebruikersccount (medewerkers_id, status_id, email, wachtwoord) VALUES (1, 1, 'Mark@mark.mark', 'wachtwoord');

-- -----------------------------------------------------
-- Table `matwente`.`computer_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`computer_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO matwente.computer_type (name) VALUES ('desktop'), ('laptop');
-- -----------------------------------------------------
-- Table `matwente`.`operating_system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`operating_system` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `operating_system_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO matwente.operating_system (operating_system_type) VALUES ('Windows 10'), ('Windows 7'), ('Linux'), ('Mac10');

-- -----------------------------------------------------
-- Table `matwente`.`computer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matwente`.`computer` (
  `pc_nummer` INT NOT NULL AUTO_INCREMENT,
  `medewerkers_id` INT NOT NULL,
  `aanschaf_datum` DATE NULL,
  `computer_type_id` INT NOT NULL,
  `operating_system_id` INT NOT NULL,
  `cpu` VARCHAR(45) NULL,
  `memory` VARCHAR(45) NULL,
  `harddisk` VARCHAR(45) NULL,
  `videocard` VARCHAR(45) NULL,
  PRIMARY KEY (`pc_nummer`, `medewerkers_id`),
  INDEX `fk_computer_medewerkers1_idx` (`medewerkers_id` ASC),
  INDEX `fk_computer_computer_type1_idx` (`computer_type_id` ASC),
  INDEX `fk_computer_operating_system1_idx` (`operating_system_id` ASC),
  CONSTRAINT `fk_computer_medewerkers1`
    FOREIGN KEY (`medewerkers_id`)
    REFERENCES `matwente`.`medewerkers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_computer_computer_type1`
    FOREIGN KEY (`computer_type_id`)
    REFERENCES `matwente`.`computer_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_computer_operating_system1`
    FOREIGN KEY (`operating_system_id`)
    REFERENCES `matwente`.`operating_system` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO matwente.computer (medewerkers_id, aanschaf_datum, computer_type_id, operating_system_id, cpu, memory, harddisk, videocard) VALUES (1, '2017-02-23', 1, 1, 'INTEL core i7', '300 GB SSD','Harddisk' , 'GTX 1080');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
